"""Create the hosted workspace foundation."""

from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001_neon_foundation'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this schema revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('auth_issuer', sa.String(length=512), nullable=False),
    sa.Column('auth_subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_issuer', 'auth_subject', name='uq_users_identity'),
    schema='smartroute'
    )
    op.create_table('workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.String(length=20), server_default='free', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("plan IN ('free', 'premium')", name='ck_workspaces_plan'),
    sa.ForeignKeyConstraint(['owner_id'], ['smartroute.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', name='uq_workspaces_owner'),
    schema='smartroute'
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['smartroute.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash'),
    schema='smartroute'
    )
    op.create_index('ix_api_keys_workspace', 'api_keys', ['workspace_id'], unique=False, schema='smartroute')
    op.create_table('provider_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('key_suffix', sa.String(length=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('openai', 'anthropic')", name='ck_credentials_provider'),
    sa.ForeignKeyConstraint(['workspace_id'], ['smartroute.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_credentials_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'provider', 'label', name='uq_credentials_label'),
    schema='smartroute'
    )
    op.create_table('requests',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('api_key_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('prompt_preview', sa.String(length=200), nullable=False),
    sa.Column('messages', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tier_chosen', sa.String(length=20), nullable=False),
    sa.Column('tier_final', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('routing_mode', sa.String(length=20), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('actual_cost_usd', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('reference_cost_usd', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('feedback', sa.Integer(), nullable=True),
    sa.Column('feedback_note', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.CheckConstraint("source IN ('api', 'playground', 'testlab', 'sdk')", name='ck_requests_source'),
    sa.CheckConstraint('actual_cost_usd >= 0 AND reference_cost_usd >= 0', name='ck_requests_costs'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_requests_confidence'),
    sa.CheckConstraint('feedback IS NULL OR feedback IN (-1, 1)', name='ck_requests_feedback'),
    sa.CheckConstraint('prompt_tokens >= 0 AND completion_tokens >= 0 AND latency_ms >= 0', name='ck_requests_usage'),
    sa.ForeignKeyConstraint(['workspace_id'], ['smartroute.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_requests_workspace_id'),
    schema='smartroute'
    )
    op.create_index('ix_requests_workspace_created', 'requests', ['workspace_id', 'created_at', 'id'], unique=False, schema='smartroute')
    op.create_table('router_models',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('artifact', sa.LargeBinary(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('feature_order', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['smartroute.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id'),
    schema='smartroute'
    )
    op.create_table('testlab_runs',
    sa.Column('run_id', sa.String(length=80), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('suite', sa.String(length=80), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('prompt_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['smartroute.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id'),
    schema='smartroute'
    )
    op.create_index('ix_testlab_workspace_created', 'testlab_runs', ['workspace_id', 'created_at', 'run_id'], unique=False, schema='smartroute')
    op.create_table('workspace_settings',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('confidence_threshold', sa.Numeric(precision=4, scale=3), server_default='0.6', nullable=False),
    sa.Column('max_escalations', sa.Integer(), server_default='1', nullable=False),
    sa.Column('reference_input_price_per_1k', sa.Numeric(precision=20, scale=10), server_default='0.0025', nullable=False),
    sa.Column('reference_output_price_per_1k', sa.Numeric(precision=20, scale=10), server_default='0.010', nullable=False),
    sa.Column('routing_mode_preference', sa.String(length=30), server_default='auto', nullable=False),
    sa.CheckConstraint("routing_mode_preference IN ('auto', 'heuristic_only', 'learned_only')", name='ck_settings_preference'),
    sa.CheckConstraint('confidence_threshold >= 0 AND confidence_threshold <= 1', name='ck_settings_confidence'),
    sa.CheckConstraint('max_escalations >= 0 AND max_escalations <= 2', name='ck_settings_escalations'),
    sa.CheckConstraint('reference_input_price_per_1k >= 0 AND reference_output_price_per_1k >= 0', name='ck_settings_prices'),
    sa.ForeignKeyConstraint(['workspace_id'], ['smartroute.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id'),
    schema='smartroute'
    )
    op.create_table('models',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('credential_id', sa.Uuid(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('input_price_per_1k', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('output_price_per_1k', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tier IN ('small', 'medium', 'large')", name='ck_models_tier'),
    sa.CheckConstraint('input_price_per_1k >= 0 AND output_price_per_1k >= 0', name='ck_models_prices'),
    sa.ForeignKeyConstraint(['workspace_id', 'credential_id'], ['smartroute.provider_credentials.workspace_id', 'smartroute.provider_credentials.id'], name='fk_models_workspace_credential', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['smartroute.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'tier', name='uq_models_workspace_tier'),
    schema='smartroute'
    )
    op.create_table('request_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.String(length=80), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('usage_details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint("kind IN ('answer', 'self_check')", name='ck_attempts_kind'),
    sa.CheckConstraint('prompt_tokens >= 0 AND completion_tokens >= 0 AND latency_ms >= 0 AND cost_usd >= 0', name='ck_attempts_usage'),
    sa.ForeignKeyConstraint(['workspace_id', 'request_id'], ['smartroute.requests.workspace_id', 'smartroute.requests.id'], name='fk_attempts_workspace_request', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'sequence', name='uq_attempts_sequence'),
    schema='smartroute'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse this schema revision only when explicitly requested by the operator."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_attempts', schema='smartroute')
    op.drop_table('models', schema='smartroute')
    op.drop_table('workspace_settings', schema='smartroute')
    op.drop_index('ix_testlab_workspace_created', table_name='testlab_runs', schema='smartroute')
    op.drop_table('testlab_runs', schema='smartroute')
    op.drop_table('router_models', schema='smartroute')
    op.drop_index('ix_requests_workspace_created', table_name='requests', schema='smartroute')
    op.drop_table('requests', schema='smartroute')
    op.drop_table('provider_credentials', schema='smartroute')
    op.drop_index('ix_api_keys_workspace', table_name='api_keys', schema='smartroute')
    op.drop_table('api_keys', schema='smartroute')
    op.drop_table('workspaces', schema='smartroute')
    op.drop_table('users', schema='smartroute')
    # ### end Alembic commands ###