"""Add owned inference audit and model options."""

from typing import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0002_owned_inference'
down_revision: str | Sequence[str] | None = '0001_neon_foundation'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this schema revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('send_temperature', sa.Boolean(), server_default='true', nullable=False), schema='smartroute')
    op.add_column('models', sa.Column('self_check_max_tokens', sa.Integer(), server_default='256', nullable=False), schema='smartroute')
    op.add_column('request_attempts', sa.Column('status', sa.String(length=20), server_default='completed', nullable=False), schema='smartroute')
    op.add_column('request_attempts', sa.Column('error_code', sa.String(length=80), nullable=True), schema='smartroute')
    op.alter_column('request_attempts', 'cost_usd',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=True,
               schema='smartroute')
    op.add_column('requests', sa.Column('status', sa.String(length=20), server_default='completed', nullable=False), schema='smartroute')
    op.add_column('requests', sa.Column('error_code', sa.String(length=80), nullable=True), schema='smartroute')
    op.alter_column('requests', 'actual_cost_usd',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=True,
               schema='smartroute')
    op.create_check_constraint('ck_models_check_budget', 'models', 'self_check_max_tokens >= 32 AND self_check_max_tokens <= 1024', schema='smartroute')
    op.create_check_constraint('ck_attempts_status', 'request_attempts', "status IN ('completed', 'failed')", schema='smartroute')
    op.create_check_constraint('ck_requests_status', 'requests', "status IN ('completed', 'failed')", schema='smartroute')
    op.create_check_constraint('ck_requests_completed_cost', 'requests', "status != 'completed' OR actual_cost_usd IS NOT NULL", schema='smartroute')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse this schema revision only when explicitly requested by the operator."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_requests_completed_cost', 'requests', schema='smartroute', type_='check')
    op.drop_constraint('ck_requests_status', 'requests', schema='smartroute', type_='check')
    op.drop_constraint('ck_attempts_status', 'request_attempts', schema='smartroute', type_='check')
    op.drop_constraint('ck_models_check_budget', 'models', schema='smartroute', type_='check')
    op.alter_column('requests', 'actual_cost_usd',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=False,
               schema='smartroute')
    op.drop_column('requests', 'error_code', schema='smartroute')
    op.drop_column('requests', 'status', schema='smartroute')
    op.alter_column('request_attempts', 'cost_usd',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=False,
               schema='smartroute')
    op.drop_column('request_attempts', 'error_code', schema='smartroute')
    op.drop_column('request_attempts', 'status', schema='smartroute')
    op.drop_column('models', 'self_check_max_tokens', schema='smartroute')
    op.drop_column('models', 'send_temperature', schema='smartroute')
    # ### end Alembic commands ###